#!/usr/bin/env python3
"""Render shell completion scripts from the starter command registry."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SAFE_COMMAND_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
SHELL_OUTPUT_NAMES = {
    "bash": "{command_name}.bash",
    "zsh": "_{command_name}",
    "powershell": "{command_name}.ps1",
}


class CompletionGenerationError(ValueError):
    """Raised when the command registry cannot be rendered safely."""


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        raise CompletionGenerationError(f"cannot read {path}: {exc}") from exc


def extract_public_commands(repo_root: Path) -> tuple[str, ...]:
    """Extract root command names from the C++ registration sources.

    `shell` is registered directly in the root configurator. The other public
    commands are derived from the registrar calls, so adding a new registrar
    updates generated completion candidates without a duplicate command list.
    """

    cli_app = read_text(repo_root / "src/app/cli_app.cpp")
    registrations = read_text(repo_root / "src/commands/register_commands.cpp")
    commands = re.findall(r'app\.add_subcommand\("([A-Za-z0-9._-]+)"', cli_app)
    commands.extend(
        re.findall(r"register_([a-z][a-z0-9_]*)_command\(\s*root\s*,", registrations)
    )
    if not commands:
        raise CompletionGenerationError("no public commands found in the command registry")
    return tuple(sorted(set(commands)))


def validate_command_name(command_name: str) -> str:
    if not SAFE_COMMAND_NAME.fullmatch(command_name):
        raise CompletionGenerationError(
            "command name must start with a letter or digit and use only letters, "
            "digits, '.', '_', or '-'"
        )
    return command_name


def render_bash(command_name: str, commands: tuple[str, ...]) -> str:
    words = " ".join(commands)
    return f'''# Generated by scripts/generate-completions.py; do not edit.
_{command_name.replace("-", "_").replace(".", "_")}_completion() {{
    local current="${{COMP_WORDS[COMP_CWORD]}}"
    COMPREPLY=( $(compgen -W "{words}" -- "$current") )
}}
complete -F _{command_name.replace("-", "_").replace(".", "_")}_completion {command_name}
'''


def render_zsh(command_name: str, commands: tuple[str, ...]) -> str:
    function_name = command_name.replace("-", "_").replace(".", "_")
    command_entries = "\n".join(f"    '{command}'" for command in commands)
    return f'''#compdef {command_name}
# Generated by scripts/generate-completions.py; do not edit.
_{function_name}() {{
  local -a commands
  commands=(
{command_entries}
  )
  _describe 'command' commands
}}
compdef _{function_name} {command_name}
'''


def render_powershell(command_name: str, commands: tuple[str, ...]) -> str:
    command_entries = ", ".join(f"'{command}'" for command in commands)
    return f'''# Generated by scripts/generate-completions.py; do not edit.
Register-ArgumentCompleter -Native -CommandName '{command_name}' -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    @({command_entries}) |
        Where-Object {{ $_ -like "$wordToComplete*" }} |
        ForEach-Object {{
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }}
}}
'''


RENDERERS = {
    "bash": render_bash,
    "zsh": render_zsh,
    "powershell": render_powershell,
}


def render(shell: str, command_name: str, commands: tuple[str, ...]) -> str:
    return RENDERERS[shell](command_name, commands)


def write_outputs(
    output_dir: Path,
    command_name: str,
    commands: tuple[str, ...],
    force: bool = False,
) -> tuple[Path, ...]:
    if output_dir.exists() and not output_dir.is_dir():
        raise CompletionGenerationError(f"output directory is not a directory: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)
    if output_dir.is_symlink():
        raise CompletionGenerationError(f"output directory must not be a symlink: {output_dir}")

    outputs: list[Path] = []
    for shell, name_template in SHELL_OUTPUT_NAMES.items():
        output_path = output_dir / name_template.format(command_name=command_name)
        if output_path.is_symlink() or (output_path.exists() and not output_path.is_file()):
            raise CompletionGenerationError(f"output path is not a regular file: {output_path}")
        if output_path.exists() and not force:
            raise CompletionGenerationError(
                f"output path already exists (pass --force to replace it): {output_path}"
            )
        output_path.write_text(render(shell, command_name, commands), encoding="utf-8")
        outputs.append(output_path)
    return tuple(outputs)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shell", choices=tuple(RENDERERS), help="shell script to print")
    parser.add_argument("--command-name", default="cli-starter", help="installed executable name")
    parser.add_argument("--output-dir", type=Path, help="write all shell scripts to this directory")
    parser.add_argument("--force", action="store_true", help="replace existing generated files")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT, help="copied starter root")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    if args.shell is None and args.output_dir is None:
        print("choose --shell to print one script or --output-dir to write all scripts", file=sys.stderr)
        return 2
    if args.shell is not None and args.output_dir is not None:
        print("--shell and --output-dir cannot be used together", file=sys.stderr)
        return 2

    try:
        command_name = validate_command_name(args.command_name)
        commands = extract_public_commands(args.repo_root)
        if args.output_dir is not None:
            for output_path in write_outputs(args.output_dir, command_name, commands, args.force):
                print(output_path)
        else:
            print(render(args.shell, command_name, commands), end="")
    except CompletionGenerationError as exc:
        print(f"completion generation failed: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
